### ISSUE TITLE
Tab to autocomplete username not working

### ISSUE THREAD

**Issue by rosslh** [5a1t/parrot#104]
Not working at all, at least on OSX/Firefox 45/Greasemonkey.

**Comment by dashed** [comment]
We've known this for a while. It works on Chrome though. 

I wasn't sure how to fix this.

**Comment by 5a1t** [comment]
Are channel switching keys working for you, Rosshill98 (control + shift left or right)?

**Comment by 5a1t** [comment]
@Rosshill98 Hey, I think I fixed it.  Please try 2.88 (just released).

**Comment by dashed** [comment]
Nah not working.

**Comment by rosslh** [comment]
Nope channel switching isn't working either

**Comment by dashed** [comment]
fixed in v2.91
