### ISSUE TITLE
Auto-completion not working as intended if the field is empty

### ISSUE THREAD

**Issue by pie3636** [5a1t/parrot#137]
If the message field is empty and I press tab, it fills in the name of the first person in the room in alphabetical order. If I press tab again, nothing else happens.

Expected behavior:
- I press Tab in the field while it's empty and nothing happens
- I press Tab in the field while it's empty and it completes it with the name of the first person in the room, but more Tab presses change the username in a cycle

**Comment by dashed** [comment]
Try v3.33

**Comment by pie3636** [comment]
The issue is fixed
