### ISSUE TITLE
Votes updating on vote buttons but not list of users

### ISSUE THREAD

**Issue by IvanFon** [5a1t/parrot#147]
As shown in this screenshot:
![screenshot](http://i.imgur.com/x0mQE2a.png)

This has happened in every room I've been in. I'm on the latest version of Parrot (3.35). As you can see, the number of votes is updating on the vote buttons but not to the left of people's usernames in the vote list.

**Comment by dashed** [comment]
Votes on list of users is inaccurate. Votes on the button are accurate.
