### ISSUE TITLE
Rate limit + Encryption = Encoded text in input

### ISSUE THREAD

**Issue by coleturner** [5a1t/parrot#151]
If you try to send encoded text, it should return the original text to the input if you hit the rate limit.

Instead it shows the encoded text, which means if you send it again it won't be decryptable.

**Comment by coleturner** [comment]
Off topic, but it would be nice if an encrypted text had a lock icon, or underline the username, because anyone can copy/paste Cipher:--- to confuse ya.

**Comment by dashed** [comment]
Thanks for the feedback. We also realize this.

---

We released encryption b/c it was somewhat working. We move fast and break things :+1:
