### ISSUE TITLE
Encryption doesn't work when using the "Send message" button

### ISSUE THREAD

**Issue by beeb** [5a1t/parrot#155]
According to /user/myclockworkuniverse the encryption of messages with @cipher doesn't happen if he clicks on the "Send message" button as opposed to hitting Enter.

**Comment by 5a1t** [comment]
Thanks @beeb , we're looking into this.

**Comment by dashed** [comment]
we're unsure how to fix this.

**Comment by 5a1t** [comment]
onMessageBoxSubmit():
            $("#robinMessageTextAlt").val(chanName + "em:"+mes2);
             $("#robinMessageText").val(chanName + "em:"+mes2);

mes2 is properly filled to this point, along with the inputs both with click and enter.

**Comment by 5a1t** [comment]
Fixed.
