### ISSUE TITLE
Feature Idea: Active user counter 

### ISSUE THREAD

**Issue by Stjerneklar** [5a1t/parrot#156]
Have an active user counter on top of user list.

havent looked at how the new user list works but if we make a counter that displays how many people are in the list, we will know how many people roughly are active at the current time.
(an interesting number to know versus the amount of people in the room)

might be as simple as pulling the length of an array or we may need to count the elements with jquery but it should be a simple thing to do.
(i would but i got a deadline)

**Comment by 5a1t** [comment]
This has been implemented.
