### ISSUE TITLE
Chat window sometimes doesn't scroll automatically

### ISSUE THREAD

**Issue by onmyouji** [5a1t/parrot#24]
The chat windows sometimes doesn't scroll automatically. I'm not sure whether it's problem with my browser or the script itself. Anyone having the same problem?

**Comment by dashed** [comment]
@onmyouji I heard of some reports on this and added a patch for it. Some folks said the patch works; and few claimed it doesn't. 

Have you updated to v2.15 to ensure it works?

**Comment by Ugleh** [comment]
Still having the issue. This is when you click on a tab.

**Comment by techguydave** [comment]
2.18 still doesn't work. Seems to scroll weird when you just let it go. Scrolls back up when you switch tabs.

**Comment by 5a1t** [comment]
Try now, a fix for this was just pushed in 2.28.

**Comment by techguydave** [comment]
Ah, I was lagging behind a bit in updates. Works perfectly! Thanks.
