### ISSUE TITLE
Parrot should provide an "all" channel, with sub-channel highlighting for those who don't prefer tabs

### ISSUE THREAD

**Issue by rosslh** [5a1t/parrot#35]
I would like to see all sub-channels in one feed with colour coding, like before, and that doesn't seem possible in the latest revision of Parrot. I've reverted my own version to 2.15.

**Comment by 5a1t** [comment]
The system tab should do this.  Check out the first tab.  If you'd like ALL (including non filtered) chat, prefix your filters with a comma ex: ,^,%chat and check System.

**Comment by dashed** [comment]
This doesn't really scale well and can be laggy for some.

**Comment by dashed** [comment]
@Rosshill98 
For this, as of v2.51, just uncheck "Filter by channels" in settings.
