### ISSUE TITLE
When switching to a new tab, Parrot does not instantly clear the textbox with the new prefix.

### ISSUE THREAD

**Issue by ShinkoNet** [5a1t/parrot#36]
Say I was in a channel that was "~" and I then switched to "&".
When I switch the tab to "&", the prefix "~" is still there in my chatbox.
When I type in the chatbox, it adds the "&" but it keeps the old prefix too, so it says "& ~ [text]" in the box.

Any way to make it so I don't have to backspace the old prefix every time I switch channels?

**Comment by dashed** [comment]
@ShinkoNet this is fixed on v2.29 now.
