### ISSUE TITLE
Blank 'System' chat

### ISSUE THREAD

**Issue by SalZorz** [5a1t/parrot#47]
![image](https://cloud.githubusercontent.com/assets/6181868/14272720/74e80510-fad3-11e5-8f4b-b39c13430b1d.png)

After browsing a few channel tabs, System just showed white. I have changed my font to Helvetica, Twitch Emotes turned on, and two usernames selected to highlight.

**Comment by dashed** [comment]
@SalZorz update to v2.40

**Comment by dashed** [comment]
closing since you said you weren't having problems anymore.
