### ISSUE TITLE
we need to organize how to handle the t17 merger

### ISSUE THREAD

**Issue by not-a-real-username** [5a1t/parrot#48]
from a comment in robintracking:

The worst thing you can do once a room is past its primary voting stage is try and convince people to vote shift. If the room loses clear majority during reevaluation, it dissolves.

So, say you have 6,000 people voting. If 3,000 vote for stay, and 2,999 vote for grow, and 1 votes for abandon, the room dissolves as if abandon had won. You can see very quickly how this could be abused.

So, you don’t need to convince half the people to stay. You need to convince like 65% of the people in both rooms, one of which will have been awaiting merge for 60 hours, to vote stay in the new room, before it ever forms. It’s a fools’ errand.

Can we add a feature like the autotracker has to Stay if room population is >5000 or something?

T17 will be the last one.

**Comment by dashed** [comment]
Wouldn't reddit be a better place to discuss this?  :confounded:

**Comment by Ugleh** [comment]
Its useless as T17 will last way past the 8th without any more merging so the people in T17 can just vote grow and leave the chat forever.

**Comment by rukku** [comment]
@2CleverUsername I think it's their decision to make. You don't get to make that choice for everyone.

**Comment by wn-mitch** [comment]
I agree with rukku
