### ISSUE TITLE
Nickname auto-complete doesn't work after latest update

### ISSUE THREAD

**Issue by bhuvan002** [5a1t/parrot#52]
Username auto-complete (after pressing tab in the chat box) isn't working anymore after commit b295f5b

**Comment by dashed** [comment]
we know.

**Comment by dashed** [comment]
@bhuvan002 should work in latest :D

**Comment by Ban3** [comment]
Still an issue in 2.59 with Firefox. Tab just focuses the next element. Tab-completion works fine with parrot disabled.

**Comment by dashed** [comment]
@Ban3 fixed as of v2.60
