### ISSUE TITLE
Shift+Left / Shift+Right interferes with selection in the textfield.

### ISSUE THREAD

**Issue by schoeggu** [5a1t/parrot#54]
When selecting text with the keyboard, you press shift+left or shift+right, wich now also changes the channel tab.

**Comment by dashed** [comment]
whoops... got a suggestion for better hotkey combo?

**Comment by schoeggu** [comment]
not really. Mabe Alt+[number] to go directly to tab with that index.
But I can live with shift+left/right.

**Comment by ZeWaka** [comment]
done, commit a89d1777683f77c6915f8dcd801792a9bd8bf2d2

**Comment by dashed** [comment]
Combo is now: (cmd | ctrl) + shift + (left + right)
