### ISSUE TITLE
Channel tab blanks when log becomes too big

### ISSUE THREAD

**Issue by mofosyne** [5a1t/parrot#58]
Channel tab blanks when log becomes too big 

For some reason, after a certain amount of time the % and # channel becomes empty. I presume there is some bug that turns the screen blank for those tabs when too many messages are logged. The other tabs are okay.

**Comment by dashed** [comment]
You mean the first System tab?

**Comment by mofosyne** [comment]
Yes... including the system tab (and the other tabs unless there is not
much post to it)

**Comment by dashed** [comment]
Is it still an issue now?

**Comment by Stjerneklar** [comment]
what is your pruning set to?

**Comment by dashed** [comment]
Should be fixed in https://github.com/5a1t/parrot/commit/c9951e00678955c060cd64c69ab092f61d9b8ca1

Please open a new issue if you run into this problem again. :+1:

**Comment by mofosyne** [comment]
It seems to be alright mate now. Oh and you fixed the scroll jumping up
too. Not bad! (hopefully it doesnt pop up again)
