### ISSUE TITLE
Tabs hover around, unfixed to top of page.

### ISSUE THREAD

**Issue by ghost** [5a1t/parrot#64]

**Comment by Stjerneklar** [comment]
starting at line 593:
`' ul#robinChannelList { list-style-type: none; margin: 0px; padding:0.3em 0;position:absolute;top:105px;width:100%; }' +
          ' ul#robinChannelList li { display: inline; }' +
          ' ul#robinChannelList li a { color: #42454a; background-color: #dedbde; border: 1px solid #c9c3ba; border-bottom: none; padding: 0.3em; text-decoration: none; }' +
          ' ul#robinChannelList li a:hover { background-color: #f1f0ee; }' +
          ' ul#robinChannelList li a.robin-chan-tab-changed { color: red; font-weight: bold; }' +
          ' ul#robinChannelList li a.robin-chan-tab-selected { color: blue; background-color: #f1f0ee; font-weight: bold; padding: 0; }' +`    

this makes the tabs same height and positions them absolutely on the line between the room name and the chat. 

-Stjerneklar

**Comment by ghost** [comment]
Legend. I'll try it out.

**Comment by ghost** [comment]
Was a tiny bug at the end. padding was set to 0 for selected tab when it should be 0.3em.

`' ul#robinChannelList li a.robin-chan-tab-selected { color: blue; background-color: #f1f0ee; font-weight: bold; padding: 0.3em; }' +`

**Comment by dashed** [comment]
@Minizium are u going to PR this?

**Comment by ghost** [comment]
Fixed in master.
