### ISSUE TITLE
Settings channel input not being saved

### ISSUE THREAD

**Issue by Jazzelhawk** [5a1t/parrot#66]
settings.channel is not being saved.

``` JSON
localStorage.getItem("robin-grow-settings")
"{"removeSpam":true, "findAndHideSpam":true, "vote":"grow", "hideVote":false, "enableUnicode":false, "maxprune":"500", "fontsize":"12", "username_bg":"",
"channel":"#,%,^",
"filterChannel":true,
"twitchEmotes":true, "spamFilters":"spam example 1, spam example 2", "fontstyle":"", "alignment":true, "mutedUsersList":["JarJarBlinked"], "tabChanColors":true, "timeoutEnabled":false}"

localStorage.getItem("robin-grow-settings")
"{"removeSpam":true, "findAndHideSpam":true, "vote":"grow", "hideVote":false, "enableUnicode":false, "maxprune":"500", "fontsize":"12", "username_bg":"", 
"channel":"#,%,^", 
"filterChannel":false, 
"twitchEmotes":true, "spamFilters":"spam example 1, spam example 2", "fontstyle":"", "alignment":true, "mutedUsersList":["JarJarBlinked"], "tabChanColors":true, "timeoutEnabled":false}"
```

As you can see `channel` remains the same even though `filterChannel` has changed.

**Comment by dashed** [comment]
If you toggle filterChannel, why would settings.channel  change?

**Comment by Jazzelhawk** [comment]
Because when you toggle a setting it calls Settings.save. The filterChannel setting being changed is to prove it did actually save. Where as changing the channel text input does nothing when saving.

**Comment by dashed** [comment]
When you type into channel textbox, it saves when the textbox is out of focus.

If you know the appropriate fix for this, feel free to create a PR, and I'll probably understand what you meant.

**Comment by Jazzelhawk** [comment]
It doesn't save when out of focus. It's supposed to save when the value in the text box changes. https://github.com/5a1t/parrot/blob/master/robin.user.js#L229

This doesn't happen for the channel text box or the spam filter text box.

**Comment by dashed** [comment]
@Jazzelhawk is the issued resolved for you?
