### ISSUE TITLE
[robin] merge messages cannot be ignored [Includes fix code but im a github noob]

### ISSUE THREAD

**Issue by Stjerneklar** [5a1t/parrot#70]
the following code will hide any message from robbin (incl the merge message)

.robin-message.robin--flair-class--no-flair.robin--message-class--action.robin--user-class--system {
    display: none;
}

i would recommend adding an option for it.

**Comment by dashed** [comment]
> the following code will hide any message from robbin (incl the merge message)

not sure if i want to do this :cry:

**Comment by Stjerneklar** [comment]
thats why i suggested it as an option :)

**Comment by ghost** [comment]
It would be nice to filter out the "[robin] no compatible room found for matching, we will count votes and check again for a match in 1 minute." spam.

**Comment by dashed** [comment]
I'm open to PRs
