### ISSUE TITLE
When someone posts two messages in quick succession, so that the name is omitted, the message isn't shown in the channel tabs.

### ISSUE THREAD

**Issue by ghost** [5a1t/parrot#74]
Let me know if this is unclear, I can get a screenshot.

**Comment by dashed** [comment]
@veganzombeh please post a screenshot :D

**Comment by ghost** [comment]
http://imgur.com/HBSz0Sl

The "#nospam testing" message should have been shown in the #nospam channel tab, but wasn't.

**Comment by dashed** [comment]
try updating to v2.60

**Comment by dashed** [comment]
@veganzombeh is this still an issue?

**Comment by X54329** [comment]
It's still an issue for me with v2.74

**Comment by ghost** [comment]
My Robin chat is a bit too active to replicate this issue. I haven't seen it since updating though.

**Comment by carreter** [comment]
This is still an issue with v2.84
