### ISSUE TITLE
Possibility of switching the autovote to STAY for tier 17 rooms only (as we likely won't get an 18th tier)?

### ISSUE THREAD

**Issue by Bo98** [5a1t/parrot#95]
Something that's getting attention is [#StayOn17](https://www.reddit.com/r/joinrobin/comments/4dhnm6/stayon17_is_the_new_stayat1k/). Currently we have a tier 16 room that's been going for over 48 hours now. Tier 17 should arrive in time before April 8th but it is very unlikely that we'll see a tier 18 before Robin is shut down. This is why #StayOn17 is being promoted as a STAY vote will be the only thing that could be achieved in the time available. It would be breaking the current stay record.

Since a mass majority of people are likely using autogrower scripts, the best chance of us achieving this would be for these scripts to vote STAY when a tier 17 room is created. However, since userscript changes only apply on refresh, **such a change should be done well before a tier 17 room is created** to allow time for people's scripts to update. You guys have an "Update Parrot" button so that helps a bit but whether people will actually click it instead of relying on the automatic update most userscript extensions have is another matter.

To avoid collapsing the current tier 16 (and lower) rooms, **this change of vote should only apply to tier 17 rooms**.

There are other autogrower scripts so they'll need to be reached out to too but I'm starting here to see if there is an interest in this as this seems to be one of the more popular scripts currently.

Thoughts?

**Comment by 5a1t** [comment]
We might implement something like this as an off-by-default feature, but we will not implement making a choice on their behalf.

**Comment by Bo98** [comment]
Fair enough, was just looking for thoughts here since it is a topic that people seem to be pushing for (judging by the threads created and the soKukuneli motto).

**Comment by Bo98** [comment]
RIP Robin.

Too late to do anything now.
