### ISSUE TITLE
Version 2.77 is not longer adding channel identifiers automatically.

### ISSUE THREAD

**Issue by jr-pe** [5a1t/parrot#96]
Since updating to version 2.77, I now need to manually add channel identifiers (.,%,^, etc.) to my chat messages.

**Edit: My apologies, this issue has already been reported -** https://github.com/5a1t/parrot/issues/92

**Comment by 5a1t** [comment]
Do you have "Apply channel filters to global chat" setting on or off?

**Comment by jr-pe** [comment]
I have tried both on and off. Neither work

**Comment by 5a1t** [comment]
We just pushed some updates, can you please try newest version and let us know if it helps?

Thank you.

**Comment by jr-pe** [comment]
The problem seems to be fixed!

Thank you.
