### ISSUE TITLE
"Right Align Usernames" actually left-aligns them

### ISSUE THREAD

**Issue by abraxas86** [5a1t/parrot#99]
The default appears to be right-aligned names.  Ticking off the box appears to make them all left-aligned.  Otherwise a pretty solid script!

**Comment by ZeWaka** [comment]
Yes. When the box is ticked it means it is right aligned.
When you untick the box it is making it no longer right-alined, aka left-aligned.

**Comment by abraxas86** [comment]
The opposite appears to be true, though.

**Comment by abraxas86** [comment]
Unchecked: http://i.imgur.com/L7ivZeW.png
Checked: http://i.imgur.com/szNbX86.png

**Comment by dashed** [comment]
that should be checkmarked :P

**Comment by dashed** [comment]
must be some race condition. you can fix it via localstorage variable in console: https://github.com/5a1t/parrot/issues/66

**Comment by dashed** [comment]
@wardrich should be fixd in     v2.97
